services:

  # api and frontend
  server:
    image: spark_board-server
    restart: always
    ports:
      - "7070:3000"
    platform: linux/amd64
    environment:
      POSTGRES_HOST: db

  # postgres database
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234

volumes:
  data:
