include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    public_member_api_docs: ignore
    always_use_package_imports: ignore

linter:
  rules:
    - prefer_relative_imports
