include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
  plugins:
    - custom_lint
  errors:
    public_member_api_docs: ignore
    always_use_package_imports: ignore
    document_ignores: ignore
    avoid_catches_without_on_clauses: ignore

linter:
  rules:
    - prefer_relative_imports
