name: spark_board_frontend
description: "A Flutter-based task management app to boost productivity"
publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_cora_riverpod: ^0.0.1-dev.7
  form_builder_validators: ^11.0.0
  go_router: ^14.6.0
  obs_state_mixin: ^0.0.1-dev.6
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
