name: spark_board_frontend
description: "A Flutter-based task management app to boost productivity"
publish_to: "none"

version: 0.0.3

environment:
  sdk: ^3.5.3

dependencies:
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.7.0
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_cora_riverpod: ^0.0.1-dev.7
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  obs_state_mixin: ^0.0.1-dev.6
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.6.1
  scroll_animator: ^0.3.0
  shared_preferences: ^2.3.3
  two_dimensional_scrollables: ^0.3.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
