openapi: 3.0.3
info:
  title: SparkBoard
  version: 1.0.0
  contact: {}
servers:
  - url: "{{base_url}}"
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: albin@mail.com
                password:
                  type: string
                  example: "12345678"
            examples:
              Login:
                value:
                  email: albin@mail.com
                  password: "12345678"
      responses:
        "200":
          description: ""
      security:
        - {}
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Signup
      description: Signup
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: albin@mail.com
                name:
                  type: string
                  example: Albin
                password:
                  type: string
                  example: "12345678"
            examples:
              Signup:
                value:
                  email: albin@mail.com
                  name: Albin
                  password: "12345678"
      responses:
        "200":
          description: ""
      security:
        - {}
  /users:
    get:
      tags:
        - User
      summary: List users
      description: List users
      operationId: listUsers
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
  /projects:
    get:
      tags:
        - Projects
      summary: List projects
      description: List projects
      operationId: listProjects
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
    post:
      tags:
        - Projects
      summary: Create project
      description: Create project
      operationId: createProject
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: The project
                name:
                  type: string
                  example: Project 1
            examples:
              Create project:
                value:
                  description: The project
                  name: Project 1
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
  /projects/{projectId}:
    delete:
      tags:
        - Projects
      summary: Delete project
      description: Delete project
      operationId: deleteProject
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
    parameters:
      - name: projectId
        in: path
        required: true
        schema:
          type: string
          example: ff4721f2-047b-4c2d-bce9-14a2c0cbb23b
  /projects/{projectId}/tasks:
    get:
      tags:
        - Tasks
      summary: List tasks
      description: List tasks
      operationId: listTasks
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
    post:
      tags:
        - Tasks
      summary: Create task
      description: Create task
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: description
                name:
                  type: string
                  example: Task 1
            examples:
              Create task:
                value:
                  description: description
                  name: Task 1
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
    parameters:
      - name: projectId
        in: path
        required: true
        schema:
          type: string
          example: 23b9f2df-c215-4d79-bceb-d12e007d0bec
  /projects/{projectId}/tasks/{taskId}:
    delete:
      tags:
        - Tasks
      summary: Delete task
      description: Delete task
      operationId: deleteTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: description
                name:
                  type: string
                  example: Task 2
            examples:
              Delete task:
                value:
                  description: description
                  name: Task 2
      responses:
        "200":
          description: ""
      security:
        - bearerAuth: []
    parameters:
      - name: projectId
        in: path
        required: true
        schema:
          type: string
          example: c7a51111-6fe9-41bd-8b17-efb10d911f46
      - name: taskId
        in: path
        required: true
        schema:
          type: string
          example: e7bc2a89-4f14-4f15-875c-67130faf2b4d
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: User
  - name: Projects
  - name: Tasks
